spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.11.249:3306/crm?serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss


logging:
  level:
    com:
      qy25: debug
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 9000
